
# Theme settings
doks:
    baseurl:
    color_theme: # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: Compose Academy
            image:
    footer:
        content:
            logo:
                text: Compose Academy
                image:
            copyright: Copyright &copy; 2020. - Joe Birch <br>All rights reserved.
        social_list:
            - network_name: twitter
              profile_url: 'https://twitter.com/hitherejoe'
    google_analytics:
        tracking_code: UA-39804005-3

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
